		#INCLUDE<P16F628.INC>
		__CONFIG 3F10
		
;DECLARACION DE ESPACIOS DE MEMORIA A USAR		
		CBLOCK	0X20
		D1									;VARIABLE CON EL VALOR DEL DISPLAY 1
		D2									;VARIABLE CON EL VALOR DEL DISPLAY 2
		D3									;VARIABLE CON EL VALOR DEL DISPLAY 3
		D4									;VARIABLE CON EL VALOR DEL DISPLAY 4
		
		N1_LOADED
		N1_D1
		N1_D2
		N1_D3
		N1_D4
		N2_LOADED
		N2_D1
		N2_D2
		N2_D3
		N2_D4
		
		RES_D1
		RES_D2
		RES_D3
		RES_D4

		INPUT_1								;PRIMER INPUT (0x0000 A 0x0FFF)
		INPUT_2								;SEGUNDO INPUT (0x0000 A 0x0FFF)
		
		RESULTADO							;RESULTADO (0x0000 A 0x0FFF)
		AUX_RES

		AUX_W
		AUX_STATUS
		CONT_AR	
		CONT_AR_2
		ENDC		

;DECLARACION DE CONSTATNES
#DEFINE BTN_G1 	PORTA,6
#DEFINE BTN_G2 	PORTA,7
#DEFINE BTN_R 	PORTA,4
#DEFINE BTN_M 	PORTB,0

#DEFINE PIN_D1 	3
#DEFINE PIN_D2 	2
#DEFINE PIN_D3 	0
#DEFINE PIN_D4 	1

#DEFINE	CTRL_DISPLAY	PORTA
#DEFINE	APAGAR_DISPLAYS CLRF	PORTA
#DEFINE HEXA	.16

;DECLARACION DE MACROS

MOSTRAR	MACRO	DIGITO,PIN
		APAGAR_DISPLAYS
		MOVF	DIGITO,W
		CALL	TAB_DISPLAY
		MOVWF	PORTB
		BSF		CTRL_DISPLAY,PIN
		ENDM

SUMAR	MACRO	DIGITO
		INCF	DIGITO,1
		MOVF	DIGITO,W
		XORLW	.16					; LIMITE DE DIGITO -1
		BTFSC	STATUS,Z			; SI LLEGO AL LIMITE Z = 0
		CLRF	DIGITO				; LO PONE EN 0 PORQUE Z = 0
		BTFSC	STATUS,Z
		CALL	LOOP_DISPLAY
		ENDM						

;INICIO DEL PROGRAMA
		
		ORG		0X00
		GOTO	CONFI
		ORG		0X04		
		GOTO	INT_TMR0
;RUTINA DE INTERRUPCION
;DESBORDA EL TIMER CADA 15ms
;MUESTRA TODOS LOS DIGITOS DE ACUERDO A LAS VARIABLES D1:4

;GUARDA STATUS Y W EN VARIABLES AUXILIARES
INT_TMR0
		BCF		INTCON,GIE
		BCF		INTCON,T0IF	
		MOVWF	AUX_W
		MOVF	STATUS,W
		MOVWF	AUX_STATUS
;MULTIPLEXADO DE DISPLAYS
		BTFSC	CTRL_DISPLAY,PIN_D1
		GOTO	MOSTRAR_D2			
		BTFSC	CTRL_DISPLAY,PIN_D2
		GOTO	MOSTRAR_D3
		BTFSC	CTRL_DISPLAY,PIN_D3
		GOTO	MOSTRAR_D4
		;GOTO 	FIN_T0I
		
		MOSTRAR	D1,PIN_D1
		GOTO 	FIN_T0I

MOSTRAR_D2
		MOSTRAR D2,PIN_D2
		GOTO 	FIN_T0I

MOSTRAR_D3
		MOSTRAR D3,PIN_D3
		GOTO 	FIN_T0I

MOSTRAR_D4
		MOSTRAR	D4,PIN_D4
		
FIN_T0I
;REINICIA TIMER Y RECUPERA STATUS Y W
		MOVLW	.198
		MOVWF	TMR0
		MOVF	AUX_STATUS,W
		MOVWF	STATUS
		MOVF	AUX_W,W
		RETFIE

;CONFIGURACION
		
CONFI
		BCF		STATUS,RP0 ; me muevo al Banco 0
		BSF		INTCON,GIE
		BSF		INTCON,T0IE

		MOVLW	0X07
		MOVWF	CMCON; CMCON SE TIENE QUE ESTABLECER EN 7 PARA USAR TODO EL PORTA
		MOVLW	.198
		MOVWF	TMR0
		
		BSF		STATUS,RP0 ; me muevo al Banco 1
		;bcf		OPTION_REG,INTEDG
		MOVLW	b'00000001'
		MOVWF	TRISB	
		MOVLW	b'11010000'
		MOVWF	TRISA
		BCF		OPTION_REG,T0CS
		BCF		OPTION_REG,PSA
		BSF		OPTION_REG,PS0
		BSF		OPTION_REG,PS1
		BSF		OPTION_REG,PS2
		BCF		STATUS,RP0 ; regreso al Banco 0


;RUTINA PRINCIPAL
;INCREMENTA DE 0 A 9 CADA DIGITO DEPENDIENDO QUE BOTON SE TOCA. 

		CLRF	PORTA
		CLRF	PORTB
		CALL 	LIMPIAR_DISPLAY
		CALL	LIMPIAR_N1_N2

; cARGA INICIAL PARA PRUEBAS -------------------- delete me !!
		MOVLW	d'1'
		MOVWF	D3
		MOVLW	d'3'
		MOVWF	D4

BOTONES
		
		BTFSC	BTN_G1			;BOTON G1 = INCREMENTA
		CALL	DEMORA_AR
		BTFSC	BTN_G1			
		SUMAR	D4				;TIENE QUE SUMAR DE 000 A FFF 
		
		BTFSC	BTN_G2			;BOTON G2 = RESTA
		CALL	DEMORA_AR
		BTFSC	BTN_G2	
		CALL	LOOP_RESTAR		;RESTAR	D4		;VERFICA LOS DISPLAY Y LE RESTA DE A 1

		BTFSC	BTN_R
		CALL	DEMORA_AR
		BTFSC	BTN_R
		CALL	REINICIAR

		BTFSC	BTN_M
		CALL	DEMORA_AR
		BTFSC	BTN_M
		CALL	SETVARIABLE

		GOTO 	BOTONES

SETVARIABLE
		;SI INPUT_1 NO ESTA VACIO GUARDAR EN INPUT_2 Y MOSTRAR RESULTADO
		;SINO GUARDAR VARIABLE EN INPUT_1 Y VOLVER A INGRESAR NUMERO
		;MOVER D2 D3 D4 A LOS ULTIMOS BITS DE INPUT
		;HACER LA RESTA Y DESPUES PONER LOS ULTIMOS BITS DEL RESULTADO EN LAS VAR DE D2 D3 D4
		;SI ES NEGATIVO D2 TIENE QUE TENER UN VALOR DE 16 (-)

		BTFSS	N1_LOADED,1
		GOTO	CARGAR_N1
		GOTO	CARGAR_N2
		
FIN_SETVAR
		RETURN

CARGAR_N1
		
		MOVF	D1,W
		MOVWF	N1_D1
		MOVF	D2,W
		MOVWF	N1_D2
		MOVF	D3,W
		MOVWF	N1_D3
		MOVF	D4,W
		MOVWF	N1_D4
		BSF 	N1_LOADED,1
		CALL	LIMPIAR_DISPLAY
		GOTO	FIN_SETVAR

CARGAR_N2
		MOVF	D1,W
		MOVWF	N2_D1
		MOVF	D2,W
		MOVWF	N2_D2
		MOVF	D3,W
		MOVWF	N2_D3
		MOVF	D4,W
		MOVWF	N2_D4
		BSF 	N2_LOADED,1
		CALL	LIMPIAR_DISPLAY
		CALL 	RESOLVER
		GOTO	FIN_SETVAR


RESOLVER
		; RESTO DIGITO 4
		MOVF	N2_D4,W
		SUBWF	N1_D4,W
		BTFSS	STATUS,C	; c = 0 SI ES NEGATIVA LA RESTA
		goto	RES_NEG4
		goto	RES_POS4

RES_NEG4
		MOVF	N1_D4,W
		SUBWF	N2_D4,W
		
		SUBLW	HEXA		; Ej : si 1-2 dio negativo entonces hago 16 -(2-1) // FALTA VER SI NO PUEDO PEDIR UNO AL SIGUIENTE DIGITO !!!!
		DECF	N1_D3,F
					; 
RES_POS4
		MOVWF	D4
		; RESTO DIGITO 3
		MOVF	N2_D3,W
		SUBWF	N1_D3,W
		BTFSS	STATUS,C
		goto	RES_NEG3
		goto	RES_POS3
		
RES_NEG3
		MOVF	N1_D3,W
		SUBWF	N2_D3,W
		SUBLW	HEXA
		DECF	N1_D2,F
	
RES_POS3
		MOVWF	D3
		; RESTO DIGITO 2
		MOVF	N2_D2,W
		SUBWF	N1_D2,W
		BTFSS	STATUS,C
		goto	RES_NEG2
		goto	RES_POS2
		

RES_NEG2
		MOVF	N1_D2,W
		SUBWF	N2_D2,W
		SUBLW	HEXA
		; SIGNO NEGATIVO --- HAY QUE VER EL SIGNO NEGATIVO 
		
		
RES_POS2
		MOVWF	D2
RES_fin	
		;;
		RETURN

REINICIAR
		CALL	LIMPIAR_DISPLAY	;LIMPIA DISPLAY Y DEJA LAS VARIABLES EN 0
		CALL	LIMPIAR_N1_N2	;
		CLRF	INPUT_1
		CLRF	INPUT_2
		CLRF	RESULTADO
		RETURN

LOOP_RESTAR
		MOVF	D4,W
		BTFSC	STATUS,Z
		goto	mepase
		DECF	D4,F
		goto	fin

mepase	
		MOVF	D3,W
		IORWF	D2,W
		BTFSC	STATUS,Z
		goto	fin
		
		MOVLW	d'15'
		MOVWF	D4			; 

		MOVF	D3,W
		BTFSC	STATUS,Z
		goto	mepase2
		DECF	D3,F
		goto	fin
		

mepase2	MOVLW	d'15'
		MOVWF	D3			;

		MOVF	D2,W
		BTFSC	STATUS,Z
		goto	mepase3
		DECF	D2,F
		goto	fin

mepase3	MOVLW	d'15'
		MOVWF	D2			; 
fin	
		RETURN

LOOP_DISPLAY
		MOVF	D4,0			;D3 (VER SI NO ESTAN MEZCLADOS EN EL REAL) 
		SUBLW	.16
		BTFSS	STATUS,W		;W = 0
		RETURN
		INCF	D3,1				; SI ES 16 EMPEZAR A SUMARLE AL TERCER DISPLAY
		MOVF	D3,W
		XORLW	.16				; LIMITE DE DIGITO -1
		BTFSC	STATUS,Z		; SI LLEGO AL LIMITE Z = 1
		CLRF	D3				; LO PONE EN 0 PORQUE Z = 1
		BTFSC	STATUS,Z			
		MOVF	D3,0			;D4 (VER) SI ES 0 SUMARLE UNO A D2
		SUBLW	.16
		BTFSS	STATUS,W
		RETURN
		INCF	D2,1
		MOVF	D2,W
		XORLW	.16
		BTFSC	STATUS,Z
		CALL	LIMPIAR_DISPLAY	;LLEGO A 0X0FFF
		RETURN

LIMPIAR_DISPLAY
		CLRF	D4
		CLRF	D3
		CLRF	D2
		CLRF	D1
		RETURN

LIMPIAR_N1_N2
		CLRF	N1_LOADED
		CLRF	N1_D1
		CLRF	N1_D2
		CLRF	N1_D3
		CLRF	N1_D4
		CLRF	N2_LOADED
		CLRF	N2_D1
		CLRF	N2_D2
		CLRF	N2_D3
		CLRF	N2_D4
	RETURN

DEMORA_AR
		MOVLW	.255
		MOVWF	CONT_AR
LOOP_AR
		MOVLW	.255
		MOVWF	CONT_AR_2
LOOP_AR_2
		DECFSZ	CONT_AR_2,1
		GOTO	LOOP_AR_2
		DECFSZ	CONT_AR,1
		GOTO	LOOP_AR
		RETURN
			
;CONVERSOR A DISPLAY
;RB1->SEG A
;RB2->SEG B 
;RB3->SEG C
;RB4->SEG D
;RB5->SEG E 
;RB6->SEG F
;RB7->SEG G

TAB_DISPLAY
		ADDWF	PCL,1
		;         GFEDCBA-
		RETLW	b'01111111'			;0
		RETLW	b'00001101'			;1
		RETLW	b'10110111'			;2
		RETLW	b'10011111'			;3
		RETLW	b'11001101'			;4
		RETLW	b'11011011'			;5
		RETLW	b'11111011'			;6
		RETLW	b'00001111'			;7
		RETLW	b'11111111'			;8
		RETLW	b'11001111'			;9
		RETLW	b'11101111'			;A
		RETLW	b'11111001'			;B
		RETLW	b'01110011'			;C
		RETLW	b'10111101'			;D
		RETLW	b'11110011'			;E
		RETLW	b'11100011'			;F
		RETLW	b'10000001'			;-		
		END